### ISSUE TITLE
Configuring simple authentication - Login not possible

### ISSUE THREAD

**Issue by StefanJaq** [Esri/geoportal-server-harvester#109]
Configured the simple authentication as described in the help:
https://github.com/Esri/geoportal-server-harvester/wiki/Installation-guide
(web.xml, Header.html, app-security.xml, authentication-simple.xml).
https://github.com/Esri/geoportal-server-harvester/wiki/Security-configuration-Simple

The loginscreen appears
I enter user and password 
NOTHING else happens

In the logfiles:
05-Dec-2019 15:49:34.317 SEVERE [https-jsse-nio-8443-exec-6] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [spring] in context with path [/omvgeoharvester] threw exception
	java.lang.IllegalArgumentException: There is no PasswordEncoder mapped for the id "null"
		at org.springframework.security.crypto.password.DelegatingPasswordEncoder$UnmappedIdPasswordEncoder.matches(DelegatingPasswordEncoder.java:244)
		at org.springframework.security.crypto.password.DelegatingPasswordEncoder.matches(DelegatingPasswordEncoder.java:198)
		at org.springframework.security.authentication.dao.DaoAuthenticationProvider.additionalAuthenticationChecks(DaoAuthenticationProvider.java:90)
		at org.springframework.security.authentication.dao.AbstractUserDetailsAuthenticationProvider.authenticate(AbstractUserDetailsAuthenticationProvider.java:166)
		at org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:175)
		at org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:200)
		at org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter.attemptAuthentication(UsernamePasswordAuthenticationFilter.java:94)
		at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:212)
		at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
		at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
		at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
		at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:74)
		at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
		at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
		at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
		at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
		at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
		at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
		at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
		at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)
		at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
		at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:357)
		at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:270)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:660)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:808)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.lang.Thread.run(Unknown Source)

**Comment by zguo** [comment]
Hi @StefanJaq, for password, do you use something like password="{noop}adminpassword"?

**Comment by StefanJaq** [comment]
Hi.
No. I removed this noop string. It‘s like password="adminpassword“.

Stefan Jaquemar
eMail: s.jaquemar@mysynergis.com
Tel: +43 1 87806 ext. 46
........................................................................................................................
Support Esri-Produkte in Österreich
eMail: esri-support@mysynergis.com
Tel: +43 1 87806 ext. 40
http://www.esri-austria.at
........................................................................................................................
SynerGIS Informationssysteme GmbH
Technologiestrasse 10 | AT - 1120 Wien | www.mysynergis.com
HG Wien, 58428z | Ust-ID: ATU 15142806 | GF: Ing. Mag. Peter Remesch
.........................................................................................................................
________________________________
Von: ZhongPing Guo <notifications@github.com>
Gesendet: Thursday, December 5, 2019 9:58:21 PM
An: Esri/geoportal-server-harvester <geoportal-server-harvester@noreply.github.com>
Cc: Jaquemar Stefan <s.jaquemar@mysynergis.com>; Mention <mention@noreply.github.com>
Betreff: Re: [Esri/geoportal-server-harvester] Configuring simple authentication - Login not possible (#109)


Hi @StefanJaq<https://github.com/StefanJaq>, for password, do you use something like password="{noop}adminpassword"?

**Comment by zguo** [comment]
can you try with {noop} to see if it helps.

**Comment by StefanJaq** [comment]
> 
> 
> can you try with {noop} to see if it helps.

Thanks, of course(!!!) that helped. Just realised that it is well documented. My mistake.
