### ISSUE TITLE
Harvesting Map Services

### ISSUE THREAD

**Issue by MapZombie** [Esri/geoportal-server-harvester#13]
This maybe a newbie question but I can't find documentation on how to harvest map services.  We have a number of map services hosted on a local server with ArcGIS REST Services that I would like to harvest.  What is the best way to go about doing this?  Is this feature even implemented yet?

**Comment by pandzel** [comment]
Recent version of the harvester has the ability to harvest ArcGIS server services through a dedicated broker. If you are using default UI, the easiest way is to add input broker "ArcGIS server services", give it some meaningful name and URL pointing to your local "rest/services" end point, for example:

https://localhost:6080/arcgis/  (that forward slash at the end of this URL might me meaningful, so it better to keep it that way).

When you create a task with such a broker and run it, it will browse the end point and create Dublin Core metadata for each recognized artifact like map service or image service. 

NOTE! If you attempt to harvest just deployed private instance of the ArcGIS server, harvester will fail to harvest such a server since that server has only self-signed SSL certificate installed. In order to get it working you have to either purchase a commercial certificate or trick Tomcat where the harvester is installed to think that this particular certificate is a valid certificate. It could be done by inserting that self-signed certificate into the 'cacerts' keystore of the Java JRE (or JDK) your Tomcat is running on, using standard Java tool called 'keytool'.

**Comment by MapZombie** [comment]
Thanks.  I was using an older version that only had CSW and WAF.  Just compiled the new version, looks promising.

**Comment by MapZombie** [comment]
I tried the new version and am now getting an error: **Error executing task** when trying to run the Task.  I am running the same tasks as I did in a earlier version of Harvester (Which had no issues).  Any ideas whats going on? See log below


```
10.101.115.59 - - [27/Sep/2016:15:12:38 -0600] "POST /geoportal-harvester-war-2.0.0/rest/harvester/tasks/7d80a058-f840-4603-b33d-6153385553e1/execute HTTP/1.1" 500 -
10.101.115.59 - - [27/Sep/2016:15:13:10 -0600] "POST /geoportal-harvester-war-2.0.0/rest/harvester/tasks/94917bfb-930d-42da-8072-1091acbe02ab/execute HTTP/1.1" 500 -
10.101.115.59 - - [27/Sep/2016:15:13:11 -0600] "POST /geoportal-harvester-war-2.0.0/rest/harvester/tasks/7d80a058-f840-4603-b33d-6153385553e1/execute HTTP/1.1" 500 -
```

**Comment by pandzel** [comment]
Code 500 indicates internal server error. So, where does that log come from? I would be looking for more information, like exception in hrv.<timestamp>.log, which may tell more specific info. Also, is this properly deployed, ie. if you open you browser and type http://<your server>:<your port>/geoportal-harvester-war-2.0.0/rest/harvester/tasks, does it give you any JSON-kind of response (even empty array)?

**Comment by MapZombie** [comment]
That log comes from localhost_access_log.  The hrv log doesnt really stamp any errors when I click run task (See below).  And http://:/geoportal-harvester-war-2.0.0/rest/harvester/tasks does give me a working JSON return.  I will try redeploying the war file.
```
Sep 27, 2016 3:51:21 PM com.esri.geoportal.commons.csw.client.impl.ProfilesLoader load
INFO: CSW profiles loaded.
Sep 27, 2016 3:52:54 PM com.esri.geoportal.commons.csw.client.impl.ProfilesLoader load
INFO: Loading CSW profiles
Sep 27, 2016 3:52:54 PM com.esri.geoportal.commons.csw.client.impl.ProfilesLoader load
INFO: CSW profiles loaded.
Sep 27, 2016 3:53:26 PM com.esri.geoportal.commons.csw.client.impl.ProfilesLoader load
INFO: Loading CSW profiles
Sep 27, 2016 3:53:26 PM com.esri.geoportal.commons.csw.client.impl.ProfilesLoader load
INFO: CSW profiles loaded.

```

**Comment by pandzel** [comment]
What is the content of the task definition? You can check it by invoking 'export' (last screenshot).

**Comment by pandzel** [comment]
There is one more thing I would do: I would delete (or move somewhere else) database files. Database is an H2 embeded databse and it's data is stored in the home folder of the user under Tomcat (or web server in general) is running. There are two database files: harvester.mv.db and harvester.trace.db. If you remove these files and restart harvester, it will create new and empty database. You will lose old definitions and you will need to define new ones, but the deployment will be really fresh.

**Comment by MapZombie** [comment]
removing the db files and redeploying the war file has gotten rid of the error!  Though it is still not harvesting, it is atleast trying.  Here is the hrv log from trying to broker Map Service -> Geoportal.
`INFO: SUBMITTING: TASK :: PROCESSOR: DEFAULT[], SOURCE: AGS[ags-host-url=http://ngismap:6080/arcgis/rest/services/Canada/base_cache/MapServer/, cred-username=xxx, cred-password=xxx], DESTINATIONS: [GPT[gpt-host-url=http://cal8783:8088/geoportal/, cred-username=gptadmin, cred-password=gptadmin, gpt-cleanup=false]], INCREMENTAL: false
Sep 28, 2016 10:07:28 AM com.esri.geoportal.harvester.engine.defaults.DefaultProcessor$DefaultProcess lambda$new$1
INFO: Started harvest: com.esri.geoportal.harvester.ags.AgsBroker@5f9909ca --> [GPT [http://cal8783:8088/geoportal//]]
Sep 28, 2016 10:07:28 AM com.esri.geoportal.harvester.support.ReportLogger started
INFO: Started processing task: PROCESS:: status: working, title: com.esri.geoportal.harvester.ags.AgsBroker@5f9909ca --> [GPT [http://cal8783:8088/geoportal//]]
Sep 28, 2016 10:07:28 AM com.esri.geoportal.harvester.support.ReportStatistics started
INFO: Harvesting of PROCESS:: status: working, title: com.esri.geoportal.harvester.ags.AgsBroker@5f9909ca --> [GPT [http://cal8783:8088/geoportal//]] started at Wed Sep 28 10:07:28 MDT 2016
Sep 28, 2016 10:07:28 AM com.esri.geoportal.harvester.support.ReportLogger completed
INFO: Completed processing task: PROCESS:: status: completed, title: com.esri.geoportal.harvester.ags.AgsBroker@5f9909ca --> [GPT [http://cal8783:8088/geoportal//]]
Sep 28, 2016 10:07:28 AM com.esri.geoportal.harvester.support.ReportStatistics completed
INFO: Harvesting of PROCESS:: status: completed, title: com.esri.geoportal.harvester.ags.AgsBroker@5f9909ca --> [GPT [http://cal8783:8088/geoportal//]] completed at Wed Sep 28 10:07:28 MDT 2016. No. succeded: 0, no. failed: 0`

So it is showing as 0 Succeeded and 0 Failed, and when checking Geoportal Catalog there is no new entry.

**Comment by pandzel** [comment]
Instead of http://ngismap:6080/arcgis/rest/services/ I would register just http://ngismap:6080/arcgis/
NOTE! Once you modify the broker, a task created based on the old broker definition won't be updated. So, you have to create a new task then run it.
Also, it turn's out it doesn't have to be run through HTTPS, at least in my environment doesn't.

**Comment by MapZombie** [comment]
Ok just tried that and its resulting in a new error and failed task:
`
Sep 28, 2016 10:52:47 AM com.esri.geoportal.harvester.support.ReportLogger error
SEVERE: Error processing task: PROCESS:: status: working, title: com.esri.geoportal.harvester.ags.AgsBroker@6fa45356 --> [GPT [http://cal8783:8088/geoportal//]]
com.esri.geoportal.harvester.api.ex.DataInputException: Error listing server content.
	at com.esri.geoportal.harvester.ags.AgsBroker.iterator(AgsBroker.java:115)
	at com.esri.geoportal.harvester.engine.defaults.DefaultProcessor$DefaultProcess.lambda$new$1(DefaultProcessor.java:126)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.fasterxml.jackson.databind.exc.InvalidFormatException: Can not construct instance of java.lang.Long from String value ("NaN"): not a valid Long value
 at [Source: {"currentVersion":10.22,"serviceDescription":"","mapName":"Layers","description":"","copyrightText":"","supportsDynamicLayers":false,"layers":[],"tables":[],"spatialReference":{"wkid":4326,"latestWkid":4326},"singleFusedMapCache":false,"initialExtent":{"xmin":-2.2117354231454307,"ymin":49.48528420902821,"xmax":-0.04197360553260565,"ymax":52.42996096150276,"spatialReference":{"wkid":4326,"latestWkid":4326}},"fullExtent":{"xmin":"NaN","ymin":"NaN","xmax":"NaN","ymax":"NaN","spatialReference":{"wkid":4326,"latestWkid":4326}},"minScale":0,"maxScale":0,"units":"esriDecimalDegrees","supportedImageFormatTypes":"PNG32,PNG24,PNG,JPG,DIB,TIFF,EMF,PS,PDF,GIF,SVG,SVGZ,BMP","documentInfo":{"Title":"","Author":"","Comments":"","Subject":"","Category":"","AntialiasingMode":"None","TextAntialiasingMode":"Force","Keywords":""},"capabilities":"Map,Query,Data","supportedQueryFormats":"JSON, AMF","exportTilesAllowed":false,"maxRecordCount":1000,"maxImageHeight":2048,"maxImageWidth":2048,"supportedExtensions":""}; line: 1, column: 432] (through reference chain: com.esri.geoportal.commons.ags.client.ServerResponse["fullExtent"]->com.esri.geoportal.commons.ags.client.ExtentInfo["xmin"])
	at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:74)
	at com.fasterxml.jackson.databind.DeserializationContext.weirdStringException(DeserializationContext.java:923)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer._parseLong(StdDeserializer.java:488)
	at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$LongDeserializer.deserialize(NumberDeserializers.java:353)
	at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$LongDeserializer.deserialize(NumberDeserializers.java:331)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:490)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:101)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:260)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:125)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:490)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:101)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:260)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:125)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3789)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2779)
	at com.esri.geoportal.commons.ags.client.AgsClient.readServiceInformation(AgsClient.java:149)
	at com.esri.geoportal.harvester.ags.AgsBroker.listResponses(AgsBroker.java:125)
	at com.esri.geoportal.harvester.ags.AgsBroker.listResponses(AgsBroker.java:132)
	at com.esri.geoportal.harvester.ags.AgsBroker.iterator(AgsBroker.java:112)
	... 2 more

Sep 28, 2016 10:52:47 AM com.esri.geoportal.harvester.support.ReportLogger completed
INFO: Completed processing task: PROCESS:: status: completed, title: com.esri.geoportal.harvester.ags.AgsBroker@6fa45356 --> [GPT [http://cal8783:8088/geoportal//]]
Sep 28, 2016 10:52:47 AM com.esri.geoportal.harvester.support.ReportStatistics completed
INFO: Harvesting of PROCESS:: status: completed, title: com.esri.geoportal.harvester.ags.AgsBroker@6fa45356 --> [GPT [http://cal8783:8088/geoportal//]] completed at Wed Sep 28 10:52:47 MDT 2016. No. succeded: 0, no. failed: 1
`

**Comment by pandzel** [comment]
This is a bug and a good one, but I think I got it fixed. Why don't you get the latest code and give it another try? (You won;t need to delete database).

**Comment by MapZombie** [comment]
Awesome it appears the bug is fixed.  I was able to successfully harvest.

**Comment by pandzel** [comment]
Thank you for making Geoportal Server 2.0 better.
