### ISSUE TITLE
Ckan harvest failure to a folder

### ISSUE THREAD

**Issue by valentinedwv** [Esri/geoportal-server-harvester#23]
https://data.noaa.gov/
http://demo.ckan.org/
====
The URI is registered in the Evaluator.js
===
```
24-Mar-2017 09:54:07.110 INFO [HARVESTING] com.esri.geoportal.harvester.support.ReportStatistics.completed Harvesting of PROCESS:: status: completed, title: PROCESSOR: DEFAULT[], SOURCE: CKAN[ckan-host-url=http://demo.ckan.org/, ckan-apikey=], DESTINATIONS: [FOLDER[folder-root-folder=D:\dev_odm\geoportal_metadata, folder-cleanup=false]], INCREMENTAL: false, IGNOREROBOTSTXT: true completed at Fri Mar 24 09:54:07 PDT 2017. No. succeded: 0, no. failed: 0
Exception in thread "HARVESTING" java.lang.RuntimeException: javax.xml.stream.XMLStreamException: Unbound namespace URI 'http://www.w3.org/1999/02/22-rdf-syntax-ns#'
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:391)
	at jdk.nashorn.api.scripting.ScriptObjectMirror.callMember(ScriptObjectMirror.java:192)
	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:381)
	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeFunction(NashornScriptEngine.java:187)
	at com.esri.geoportal.commons.meta.js.BaseJSMetaBuilder.execute(BaseJSMetaBuilder.java:67)
	at com.esri.geoportal.commons.meta.js.BaseJSMetaBuilder.create(BaseJSMetaBuilder.java:53)
	at com.esri.geoportal.harvester.ckan.CkanBroker$CkanIterator.next(CkanBroker.java:224)
	at com.esri.geoportal.harvester.engine.defaults.DefaultProcessor$DefaultProcess.lambda$new$1(DefaultProcessor.java:137)
	at com.esri.geoportal.harvester.engine.defaults.DefaultProcessor$DefaultProcess$$Lambda$590/4609631.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.xml.stream.XMLStreamException: Unbound namespace URI 'http://www.w3.org/1999/02/22-rdf-syntax-ns#'
	at com.ctc.wstx.sw.SimpleNsStreamWriter.writeStartOrEmpty(SimpleNsStreamWriter.java:231)
	at com.ctc.wstx.sw.BaseNsStreamWriter.writeStartElement(BaseNsStreamWriter.java:306)
	at com.esri.geoportal.commons.meta.js.XmlBuilder.writeStartElement(XmlBuilder.java:78)
	at jdk.nashorn.internal.scripts.Script$Recompilation$58$677A$\^eval\_.create(<eval>:30)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:638)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:229)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:387)
	... 9 more

```

**Comment by zguo** [comment]
I tried to harvest the two sites, it worked fine with me.

not sure if related to particular settings, can you provide some details about your environment, java version, app server, os, etc.

**Comment by valentinedwv** [comment]
Server version:        Apache Tomcat/8.0.27
 Server built:          Sep 28 2015 08:17:25 UTC
 Server number:         8.0.27.0
 OS Name:               Windows 8.1
 OS Version:            6.3
Architecture:          x86
 Java Home:             C:\Program Files (x86)\Java\jdk1.8.0_45\jre
 JVM Version:           1.8.0_45-b15
 JVM Vendor:            Oracle Corporation

**Comment by valentinedwv** [comment]
Ran the 2.5 release, with the latest java 8 (111).
No issues.

Local build from tree failing. Could be some XML conflict, as I'm developing harvester for OAI and DataOne.

**Comment by valentinedwv** [comment]
Yes, my end. Clean copy of tree shows only Validation exception.
