### ISSUE TITLE
Validation error on every file unc/waf

### ISSUE THREAD

**Issue by MapZombie** [Esri/geoportal-server-harvester#29]
Trying to harvest a folder path through UNC
c:\harvest and \\hostname\harvest
I get a validation error on every file (thousands)

The same thing happens if I try it through WAF.

These files upload without issue through Geoportal and give no validation issues. I've pulled the latest commit and compiled it.

From the logs:
`
17-Jul-2017 16:50:22.574 WARNING [HARVESTING] com.esri.geoportal.harvester.engine.defaults.DefaultProcessor$DefaultProcess.lambda$null$0 Failed harvesting id: C:\Harvest\calna1\gisdata_\GIS\GIS_Services\Canada\Regional\Technical_Graphics\T00603.ai.xml, modified: Mon Jul 17 11:35:58 MDT 2017, source URI: file:///C:/Harvest/calna1/gisdata_/GIS/GIS_Services/Canada/Regional/Technical_Graphics/T00603.ai.xml, broker URI: UNC:Harvest/calna1/gisdata_/GIS/GIS_Services/Canada during PROCESSOR: DEFAULT[], SOURCE: UNC[unc-root-folder=C:\Harvest\calna1\gisdata_\GIS\GIS_Services\Canada, unc-pattern=], DESTINATIONS: [GPT[gpt-host-url=http://calwgist08:8080/gp2, cred-username=gptadmin, cred-password=*****, gpt-index=, gpt-cleanup=false, gpt-accept-xml=true, gpt-accept-json=false]], INCREMENTAL: false, IGNOREROBOTSTXT: false
17-Jul-2017 16:50:22.574 SEVERE [HARVESTING] com.esri.geoportal.harvester.support.ErrorLogger.logError Error processing task: PROCESS:: status: working, title: PROCESSOR: DEFAULT[], SOURCE: UNC[unc-root-folder=C:\Harvest\calna1\gisdata_\GIS\GIS_Services\Canada, unc-pattern=], DESTINATIONS: [GPT[gpt-host-url=http://calwgist08:8080/gp2, cred-username=gptadmin, cred-password=*****, gpt-index=, gpt-cleanup=false, gpt-accept-xml=true, gpt-accept-json=false]], INCREMENTAL: false, IGNOREROBOTSTXT: false | Validation exception.
 com.esri.geoportal.harvester.gpt.GptBroker$2: Validation exception.
	at com.esri.geoportal.harvester.gpt.GptBroker.publish(GptBroker.java:175)
	at com.esri.geoportal.harvester.api.base.BrokerLinkActionAdaptor.push(BrokerLinkActionAdaptor.java:64)
	at com.esri.geoportal.harvester.api.base.SimpleLink.push(SimpleLink.java:71)
	at com.esri.geoportal.harvester.engine.defaults.DefaultProcessor$DefaultProcess.lambda$null$0(DefaultProcessor.java:140)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at com.esri.geoportal.harvester.engine.defaults.DefaultProcessor$DefaultProcess.lambda$new$1(DefaultProcessor.java:138)
	at java.lang.Thread.run(Thread.java:748)`

Geoportal.log
`2017-07-17 17:19:53,253 DEBUG [com.esri.geoportal.context.AppResponse] - Validation exception.
2017-07-17 17:19:53,269 DEBUG [com.esri.geoportal.context.AppResponse] - Validation exception.
2017-07-17 17:19:53,284 DEBUG [com.esri.geoportal.context.AppResponse] - Validation exception.
2017-07-17 17:19:53,300 DEBUG [com.esri.geoportal.context.AppResponse] - Validation exception.
2017-07-17 17:19:53,316 DEBUG [com.esri.geoportal.context.AppResponse] - Validation exception.`

I have tried to:
-Delete the index
-Restarted elasticsearch
-Restarted Tomcat
-Restarted Server
-Checked permissions on folder
-Recompiled Harvester
-Deleted the harvester.db files 

Things that are working:
-Harvesting into a local folder

**Comment by zguo** [comment]
can you please provide a few of the files that is having the issue.

**Comment by MapZombie** [comment]
[CA2732.mxd.zip](https://github.com/Esri/geoportal-server-harvester/files/1156301/CA2732.mxd.zip)
Here is an example of one of the files. I can upload these individually with no problem through Geoportal, it is harvester that is throwing a generic validation error.

**Comment by MapZombie** [comment]
Other notes: 
**If I run tomcat on a different port than 8080, lets say 8088. I get a connection refused error.**

`17-Jul-2017 15:11:10.092 SEVERE [HARVESTING] com.esri.geoportal.harvester.support.ErrorLogger.logError Error processing task: PROCESS:: status: working, title: PROCESSOR: DEFAULT[], SOURCE: UNC[unc-root-folder=C:\Harvest\calna1\gisdata_\GIS\GIS_Services, unc-pattern=], DESTINATIONS: [GPT[gpt-host-url=http://calwgist08:8080/gp2, cred-username=gptadmin, cred-password=*****, gpt-cleanup=false]], INCREMENTAL: false, IGNOREROBOTSTXT: false | Error publishing data: id: C:\Harvest\calna1\gisdata_\GIS\GIS_Services\TEST.mxd.xml, modified: Mon Jul 17 11:35:10 MDT 2017, source URI: file:///C:/Harvest/calna1/gisdata_/GIS/GIS_Services/TEST.mxd.xml, broker URI: UNC:Harvest/calna1/gisdata_/GIS/GIS_Services
 com.esri.geoportal.harvester.api.ex.DataOutputException: Error publishing data: id: C:\Harvest\calna1\gisdata_\GIS\GIS_Services\TEST.mxd.xml, modified: Mon Jul 17 11:35:10 MDT 2017, source URI: file:///C:/Harvest/calna1/gisdata_/GIS/GIS_Services/TEST.mxd.xml, broker URI: UNC:Harvest/calna1/gisdata_/GIS/GIS_Services/
	at com.esri.geoportal.harvester.gpt.GptBroker.publish(GptBroker.java:180)
	at com.esri.geoportal.harvester.api.base.BrokerLinkActionAdaptor.push(BrokerLinkActionAdaptor.java:64)
	at com.esri.geoportal.harvester.api.base.SimpleLink.push(SimpleLink.java:71)
	at com.esri.geoportal.harvester.engine.defaults.DefaultProcessor$DefaultProcess.lambda$null$0(DefaultProcessor.java:140)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
	at com.esri.geoportal.harvester.engine.defaults.DefaultProcessor$DefaultProcess.lambda$new$1(DefaultProcessor.java:138)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to calwgist08:8080 [calwgist08/10.13.193.102, calwgist08/0:0:0:0:0:0:0:1] failed: Connection refused: connect
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:158)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at com.esri.geoportal.commons.gpt.client.Client.execute(Client.java:477)
	at com.esri.geoportal.commons.gpt.client.Client.generateToken(Client.java:528)
	at com.esri.geoportal.commons.gpt.client.Client.getAccessToken(Client.java:502)
	at com.esri.geoportal.commons.gpt.client.Client.createQueryUri(Client.java:465)
	at com.esri.geoportal.commons.gpt.client.Client.query(Client.java:424)
	at com.esri.geoportal.commons.gpt.client.Client.queryIds(Client.java:397)
	at com.esri.geoportal.commons.gpt.client.Client.queryIds(Client.java:381)
	at com.esri.geoportal.commons.gpt.client.Client.publish(Client.java:142)
	at com.esri.geoportal.harvester.gpt.GptBroker.publish(GptBroker.java:165)
	... 7 more
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:74)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
	... 25 more`

**Comment by zguo** [comment]
I tried the metadata you provided, it seems working fine for me on my test instance, tried from unc (local folder) to geoportal 2.5.

**Comment by MapZombie** [comment]
Any clue what it could be? Seems like something between harvester-geoportal-elasticsearch is broken?

**Comment by MapZombie** [comment]
Or there is something on the network/permission? But the error tells me very little.

**Comment by MapZombie** [comment]
another note I am using an Administrator user account. It starts with a $, if that makes any difference.

**Comment by MapZombie** [comment]
Rolling back to an older version "Harvester 2.0" allowed me to harvest to the Geoportal...
Not sure what changes were made or why there are compatibility issues. I was using Geoportal 2.5

**Comment by zguo** [comment]
we just checked in a fix should resolve the issue, please try.

**Comment by MapZombie** [comment]
Yes just tried with the fix it looks like its working. Thanks.
