### ISSUE TITLE
Issue with  SSL

### ISSUE THREAD

**Issue by valentinedwv** [Esri/geoportal-server-harvester#94]
Some suggest self signed. This is signed by rapid ssl.

https://data.ioos.us/csw
---
```
com.esri.geoportal.harvester.api.ex.DataInputException: Error reading data.
	at com.esri.geoportal.harvester.csw.CswBroker$CswIterator.hasNext(CswBroker.java:189)
	at com.esri.geoportal.harvester.engine.defaults.DefaultProcessor$DefaultProcess.lambda$new$11(DefaultProcessor.java:150)
	at com.esri.geoportal.harvester.engine.defaults.DefaultProcessor$DefaultProcess$$Lambda$172/17671274.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
...
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:145)
```

**Comment by valentinedwv** [comment]
Used InstallCert to install certificate.

http://s-n-ushakov.blogspot.com/2013/11/yet-another-installcert-for-java-now.html

Not sure if an alert about the issue would be appropriate. If not, close.

**Comment by pandzel** [comment]
SSL/TLS certificate exception is quite typical. It tells that Java considers particular endpoint insecure. It happens if self-signed certificate has been installed and, in some rare occasions, even if certificate which appears to be valid. In such cases the only reasonable solution is to install that certificate in keystore which is equivalent to telling Java it's save to use that endpoint. We recommend to use JDK keytool although any other utility might work.
